version: '2'
services:
  shard02-b:
    image: mongo:5.0
    container_name: shard-02-node-b
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02
    volumes:
      - ./scripts:/scripts
    ports:
      - 27127:27017
    networks:
      - mongodbshardedcluster_default

networks:
  mongodbshardedcluster_default:
    external: true