version: '2'
services:
  router01:
    image: mongo:5.0
    container_name: router-01
    command: mongos --port 27017 --configdb rs-config-server/configsvr01:27017,configsvr02:27017,configsvr03:27017 --bind_ip_all
    ports:
      - 27117:27017
    volumes:
      - ./scripts:/scripts
    networks:
      - mongodbshardedcluster_default
  router02:
    image: mongo:5.0
    container_name: router-02
    command: mongos --port 27017 --configdb rs-config-server/configsvr01:27017,configsvr02:27017,configsvr03:27017 --bind_ip_all
    volumes:
      - ./scripts:/scripts
    ports:
      - 27118:27017
    links:
      - router01
    networks:
      - mongodbshardedcluster_default

networks:
  mongodbshardedcluster_default:
    external: true